### ISSUE TITLE
Decimal a Keyword

### ISSUE THREAD

**Issue by corbinu** [purplecabbage/valid-identifier#1]
Hello,

I am curious why 'decimal' is considered a banned key word I seem to be able to create App id's with it in the identifier for Xcode, Android Studio, VisualStudio and Appcelerator Titanium.

What is blocking here and what can I do to help?

**Comment by purplecabbage** [comment]
Decimal is a keyword in C# ( https://msdn.microsoft.com/en-us/library/364x0z75.aspx )
Visual Studio will not allow C# to use 'decimal' in a package name.
This affects WP8 cordova apps.

**Comment by corbinu** [comment]
Thanks much for the response. I was not running into an issue as was creating a Windows app rather then a WP8 app. I will patch around for now and will reopen when WP8 is removed from Cordova though I do not expect that will happen soon.

**Comment by purplecabbage** [comment]
'dec1mal' is valid!

**Comment by corbinu** [comment]
thanks :) given that I don't plan to support wp8 anyway figuring is easier to just override and keep the package names properly consistent with my domain
